language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
deploy:
  provider: openshift
  user: romashenko_kot@hotmail.com
  password: victory_OS # can be encrypted
  domain: konstantintodos
